[versions]
velocity = "3.4.0-SNAPSHOT"
vanishBridge = "2.0-SNAPSHOT"

[libraries]
velocityApi = { group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity" }
vanishBridgeHelper = { group = "uk.co.notnull", name = "VanishBridge-helper", version.ref="vanishBridge" }

[plugins]